---

- name: Download Erlang Solutions repo
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /tmp

- name: Add Erlang Solutions repo 
  command: dpkg -i erlang-solutions_1.0_all.deb
  args:
    chdir: /tmp

- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Install erlang
  apt: name=esl-erlang state=present

- name: Install elixir
  apt: name=elixir state=present

