- name: install nginx
  apt: name=nginx update_cache=yes

- name: creates directory
  file: path=/var/app state=directory owner={{ubuntu_common_deploy_user_name}} group={{ubuntu_common_deploy_user_name}} mode=0775

- name: change nginx available folder ownership 
  file: path=/etc/nginx/sites-available state=directory owner={{ubuntu_common_deploy_user_name}} group={{ubuntu_common_deploy_user_name}} mode=0775

- name: change nginx enabled folder ownership 
  file: path=/etc/nginx/sites-enabled/ state=directory owner={{ubuntu_common_deploy_user_name}} group={{ubuntu_common_deploy_user_name}} mode=0775

- name: check default site file exists
  stat:
    path: /etc/nginx/sites-available/default
  register: site

- name: remove nginx default
  shell: rm /etc/nginx/sites-available/default
  when: site.stat.exists