- name: install leiningen
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /usr/local/bin/lein
    mode: 0755

- name: install boot
  get_url:
    url: https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
    dest: /usr/local/bin/boot.sh
    mode: 0755
