UBUNTU_COMMON_ROOT_PASSWORD: '{{ hash_sudo_pass }}' 
UBUNTU_COMMON_DEPLOY_PASSWORD: '{{ hash_sudo_pass }}'
ubuntu_common_deploy_user_name: deploy
ubuntu_common_deploy_public_keys:
    - ../public_keys/unclebean_rsa.pub
    - ../public_keys/developer_rsa.pub

ubuntu_common_required_packages:
    - ufw
    - fail2ban
    - unattended-upgrades
    - logwatch
    - zip
    - unzip

ubuntu_common_optional_packages:
    - mosh
    - vim
    - tmux

ubuntu_common_ssh_port: 22
ubuntu_common_mosh_from_port: 60000
ubuntu_common_mosh_to_port: 60010

authorized_keys_path: /home/deploy/.ssh/authorized_keys