- name: load node source
  get_url:
    url=https://deb.nodesource.com/setup_8.x
    dest=/tmp/nodejs_setup_8.x
    mode=755

- name: execute nodejs shell
  shell: /tmp/nodejs_setup_8.x
  args:
    executable: /bin/bash

- name: install nodejs
  apt: name=nodejs force=yes

- name: install pm2
  shell: npm install pm2 -g
  args:
    executable: /bin/bash