- hosts: all
  gather_facts: false
  roles:
    - role: foundation
      become: true
    - role: monit
      become: true
    - role: nodejs
      become: true
    - role: java
      become: true
    - role: clojure
      become: true
    - role: nginx
      become: true
    
